namespace LEDs
{
    delegate void LEDsStateChangedEventHandler(Boolean on, Boolean auto_idle, Boolean auto_levels, Single warm, Single cool);

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        event LEDsStateChangedEventHandler LEDsStateChanged;

        void SetState(Boolean on, Boolean auto_idle, Boolean auto_levels, Single warm, Single cool);

        void Show();
    }
}
